apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mediacms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwsgi
  namespace: mediacms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-short
  namespace: mediacms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-long
  namespace: mediacms
spec:
  replicas: 1
