apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-files-pvc
  namespace: mediacms-prod
spec:
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: mediacms-prod
spec:
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacms-db-pvc
  namespace: mediacms-prod
spec:
  resources:
    requests:
      storage: 50Gi
