apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediacms

commonLabels:
  app.kubernetes.io/name: mediacms
  app.kubernetes.io/part-of: mediacms
  app.kubernetes.io/managed-by: argocd

resources:
  - route.yaml
