apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediacms
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: mediacms
    app.kubernetes.io/part-of: mediacms
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mediacms-io/mediacms.git
    targetRevision: main
    path: deploy/openshift/base
    kustomize:
      labels:
        - includeSelectors: true
          pairs:
            app.kubernetes.io/managed-by: argocd
            app.kubernetes.io/name: mediacms
            app.kubernetes.io/part-of: mediacms
  destination:
    server: https://kubernetes.default.svc
    namespace: mediacms
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
