apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
  namespace: mediacms
  labels:
    app.kubernetes.io/name: mediacms
    app.kubernetes.io/part-of: mediacms
    app.kubernetes.io/managed-by: argocd
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-binding
  namespace: mediacms
  labels:
    app.kubernetes.io/name: mediacms
    app.kubernetes.io/part-of: mediacms
    app.kubernetes.io/managed-by: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: mediacms
