apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediacms


resources:
- mediacms-application.yaml
- namespace.yaml
- mediacms-config.yaml
- mediacms-secrets.yaml
- imagemagick-policy.yaml
- uwsgi-config.yaml
- web-config.yaml
- ../builds
- ../components
- ../networking
- ../storage
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mediacms
    app.kubernetes.io/part-of: mediacms
