apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediacms


resources:
- namespace.yaml
- mediacms-config.yaml
- mediacms-image-config.yaml
- mediacms-secrets.yaml
- imagemagick-policy.yaml
- uwsgi-config.yaml
- web-config.yaml
- job-reader-role.yaml
- ../storage
- ../builds
- ../components
- ../networking

# Replace container image references with value from mediacms-image-config ConfigMap
# This replaces the image field in the first container (index 0) of all Deployments and Jobs
# All MediaCMS components have the mediacms container as the first (and only) container
replacements:
- source:
    kind: ConfigMap
    name: mediacms-image-config
    fieldPath: data.image
  targets:
  - select:
      kind: Deployment
      labelSelector: default-image=mediacms
    fieldPaths:
     - spec.template.spec.containers.[name=mediacms].image
  - select:
      kind: Job
      labelSelector: default-image=mediacms
    fieldPaths:
     - spec.template.spec.containers.[name=mediacms].image

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mediacms
    app.kubernetes.io/part-of: mediacms
